### ISSUE TITLE
Publish on CRAN

### ISSUE THREAD

**Issue by pawelru** [shinyTree/shinyTree#112]
The version on CRAN is pretty old one - `0.2.7` more than 2 years old as for now. Also it's missing an important bugfix https://github.com/shinyTree/shinyTree/commit/20ee8af09f642465e8c099c4a197a86a8c2a8ccc that fails my CI builds.

Would you be able to submit the newest version on CRAN?

**Comment by ChrKoenig** [comment]
Any progress on this? If I'm not mistaken, the referenced bug in 0.27 causes an error `No handler registered for type *:shinyTree` that can only be fixed by loading the package with `library(shinyTree)`. This is problematic when using shinyTree in an R package.

**Comment by pepijn-devries** [comment]
As my Shiny server only allows me to use packages available from CRAN, I'm also hoping to see a new release there. The latest release on CRAN does not support the use of shinyTree in module servers, which is fixed in the developmental version on Github. Is a new release scheduled in the near future?

**Comment by bellma-lilly** [comment]
I just submitted the current release to CRAN
