### ISSUE TITLE
shinyTree does not work with reactivevalue  

### ISSUE THREAD

**Issue by yilmazbrs** [shinyTree/shinyTree#20]
if the list object has been created dynamically, we cannot get the selection contents using get_selected()
ui=shinyUI(
  pageWithSidebar(
    # Application title
    headerPanel("shinyTree with 'selected' input"),
    
    sidebarPanel(
      actionButton("loadlist", "Load list")
    ),
    mainPanel(
      "Currently Selected:",
      verbatimTextOutput("selTxt"),
      hr(),
      shinyTree("tree")
    )
  ))
server=shinyServer(function(input, output, session) {
  MY <- reactiveValues(value= NULL)
  observeEvent(input$loadlist,{
    MY$value <-list(
      root1 = structure("123"),
      root2 = list(
        SubListA = list(leaf1 = "", leaf2 = "", leaf3=""),
        SubListB = list(leafA = "", leafB = "")
      )
    )
  })
  log <- c(paste0(Sys.time(), ": Interact with the tree to see the logs here..."))
  
  output$tree <- renderTree({
    if(is.null(MY$value)) return()
    MY$value
  })
  
  output$selTxt <- renderText({
    tree <- input$tree
    if (is.null(tree)){
      "None"
    } else{
      unlist(get_selected(tree))
    }
  })
})

**Comment by schaffman5** [comment]
Try the fork I just created today (see example 11-tree-update): https://github.com/schaffman5/shinyTree.

**Comment by scizmeli** [comment]
@schaffman5, amazing work. your example works well. 

One thing though, is that you encoded your data by hand as a JSON string. However we are generating data dynamically as an R list. I have tried to convert my list to JSON string using jsonlite::toJSON() but shinyTree seems to not recognize that. Do you have a solution for this problem? We are nearly there, just need this one last touch.


library(shiny)
library(shinyTree)
library(jsonlite)

ui=shinyUI(
  pageWithSidebar(
    # Application title
    headerPanel("shinyTree with 'selected' input"),

    sidebarPanel(
      actionButton("loadlist", "Load list")
    ),
    mainPanel(
      "Currently Selected:",
      verbatimTextOutput("selTxt"),
      hr(),
      shinyTree("tree")
    )
  ))

server=shinyServer(function(input, output, session) {
  MY <- reactiveValues(value= NULL)
  observeEvent(input$loadlist,{
    MY$value <-jsonlite::toJSON(list(
      root1 = structure("123"),
      root2 = list(
        SubListA = list(leaf1 = "", leaf2 = "", leaf3=""),
        SubListB = list(leafA = "", leafB = "")
      )
    ))
    updateTree(session,"tree",MY$value)

  })

  # Tree is initialized without nodes
  output$tree <- renderEmptyTree()

  output$selTxt <- renderText({
    tree <- input$tree
    if (is.null(tree)){
      "None"
    } else{
      unlist(get_selected(tree))
    }
  })
})
shiny::shinyApp(ui=ui, server = server)
`
```

**Comment by schaffman5** [comment]
Yes, jsTree (the underlying javascript library) seems to be quite sensitive to malformed JSON.  See the JSON tree specs here: https://www.jstree.com/docs/json/ and make sure your json encoding approach produces exactly what is expected (either the standard or alternative JSON formats should work).

**Comment by scizmeli** [comment]
OK, I understand. I am sure I can work that out. Thanks a million for your kindly help.

@schaffman5' I guess you provided a wonderful input to shinyTree that was missing before. But for a best integration into shinyTree, if I understand correctly, @trestletech's renderTree() accepts an R list as input but your updateTree() requires a JSON script. For the sake of consistence, would not it be best if the inputs are harmonized so that the users know what to input? I guess an R list is the way to go. 
@schaffman5 and @trestletech, I would be curious to know your opinion about that. And of course, would be very interested in seeing @schaffman5's contribution in shinyTree.

**Comment by schaffman5** [comment]
I agree it would provide consistency to accept an R list and wouldn't be hard to add.  The inconsistency is really that the original implementation accepts only a nested tree data model and initializes the tree as HTML tags, whereas the emptyTree/updateTree method make use of a jsTree API call that accepts tree data in either the standard nested JSON format or the alternative JSON formats.

I personally think the alternative format is much cleaner and readable, especially when pulling data from a database (which is how I'm using it myself and in my last comment above).  I'd suggest abandoning the HTML tag initialization approach in favor of the API call unless there is a performance hit for really large trees or some other reason.  This would allow both JSON formats to be accepted and specified in an R wrapper function.  The initialization then becomes a one-liner in the jsTree init function (data:[<json-tree>]).  Curious what @trestletech thinks since he did a great job with the original library.

**Comment by scizmeli** [comment]
Well explained. Let's hear what  @trestletech has to say about it :)

**Comment by scizmeli** [comment]
Hi  @trestletech. Any comments about which way to go to make shinyTree updatable within a shiny session? Do you have interest in incorporating @schaffman5  's work anytime soon?

**Comment by timelyportfolio** [comment]
Given no comments or progress on this, perhaps @trestletech might be willing to hand over to the community, or we could do `shinyTree2`.  I have a current use case, and really this is the only viable option in the `jquery` universe for checkbox tree select.

I updated to jsTree `3.3.5` and everything works that I tested.

**Comment by schaffman5** [comment]
#21 closes this issue.
