### ISSUE TITLE
Support custom node icons.

### ISSUE THREAD

**Issue by trestletech** [shinyTree/shinyTree#9]
From #4 

> Finally, would it be possible to use a cutom icon by specifying a path to a suitable png? I think in the original jsTree implementation this is possible.

**Comment by theRanalyst** [comment]
I came here looking to ask the same question. I know that it's possible to set up your list such that `NodeA = structure("", sticon="some font awesome icon")` which can than be modified using CSS to give it color and such. However, I don't like the aesthetics of that because the icons from jsTree are so much more pleasing to the eye. 

To try to fix this, I thought I could just download icons and save them in the `shinyTree/www/jsTree-3.0.2/themes/default` folder and the reference them as a url with the `sticon` argument, but that's not working. Is there a way to pass a URL to the list element that gets passed as the `background-image` style?

**Comment by fbreitwieser** [comment]
jsTree has a types plugin that allows to specify the node icons for groups: https://www.jstree.com/plugins

**Comment by YsoSirius** [comment]
I can include glyphicon & fa icons without a problem (_3c33f61_). But when trying to include a local image it treats it like a fa-icon.

This node-icon
`leafB = structure("",sttype="default",sticon="shinyTree/icon.png")`

will become this html-icon
`<i class="jstree-icon jstree-themeicon jstree-themeicon-custom" role="presentation" style="background-image: url("fa fa-shinyTree/icon.png"); background-position: center center; background-size: auto auto;"></i>`.

How can i prevent the image from being wrapped in `url("fa fa-...")`?

**Comment by bellma-lilly** [comment]
I have a pull request submitted which addresses the icon issue.

On Oct 15, 2018, at 6:30 PM, YsoSirius <notifications@github.com<mailto:notifications@github.com>> wrote:


EXTERNAL EMAIL: Use caution before replying, clicking links, and opening attachments.


I can include glyphicon & fa icons without a problem (3c33f61<https://github.com/shinyTree/shinyTree/commit/3c33f612aeb551c1aba75b9f86bc17fde9f69e28>). But when trying to include a local image it treats it like a fa-icon.

This node-icon
leafB = structure("",sttype="default",sticon="shinyTree/icon.png")

will become this html-icon
<i class="jstree-icon jstree-themeicon jstree-themeicon-custom" role="presentation" style="background-image: url("fa fa-shinyTree/icon.png"); background-position: center center; background-size: auto auto;"></i>.

How can i prevent the image from being wrapped in url("fa fa-...")?

**Comment by YsoSirius** [comment]
Why not make the `fixIconName` very easy and leave it like this:

```
fixIconName <- function(icon){
  if(!is.null(icon)){
    icon
  }else{
    NULL
  }
}
```

This works for me with fa, glyphicon and local images just by setting:

> attr(x,"sticon") <- "glyphicon glyphicon-leaf"
> attr(x,"sticon") <- "fa fa-signal"
> attr(x,"sticon") <- 'image.png'

**Comment by bellma-lilly** [comment]
Current users expect "signal" to be changed to "fa fa-signal".  My more complex function supports backward compatibility.
